FROM bbs-base

ENV TERM=dumb EDITOR=ex VISUAL=ex
RUN apk add bash curl mailx vim runuser util-linux msmtp less
COPY entrypoint.sh /entrypoint.sh
COPY profile /etc/profile
# only for s-nail
#COPY mail.rc msmtprc /etc/
COPY commands/* /usr/bin/
RUN ln -sf /usr/bin/msmtp /usr/sbin/sendmail
ENTRYPOINT ["bash", "/entrypoint.sh"]
CMD ["/bin/bash"]
